Repository siyuan-note/siyuan, pull requests merged in 2022-11, with the labels that each got.

#6447 用 `os.ReadDir` 替换 `Readdir(-1)`
  kernel/bazaar/icon.go
  kernel/bazaar/template.go
  kernel/bazaar/theme.go
  kernel/bazaar/widget.go
  kernel/model/appearance.go
Labels: Refactor

#6464 行内元素的下划线颜色继承当前元素前景颜色
  app/src/assets/scss/_typography.scss
  app/src/assets/scss/_wysiwyg.scss
Labels: Enhancement

#6633 :octocat: Update link address of CI/CD release changelogs
  scripts/parse-changelog.py
Labels: Document
