Repository siyuan-note/siyuan, pull requests merged in 2023-07, with the labels that each got.

#8763 KaTex macro definition setting do not check spelling
  app/src/config/editor.ts
Labels: Enhancement

#8805 API `/api/file/readDir` support for returning symbolic link information
  API.md
  API_zh_CN.md
  kernel/api/file.go
  kernel/util/file.go
Labels: Enhancement

#8841 Kernel API `/api/export/exportResources` to export files and folders
  API.md
  API_zh_CN.md
  kernel/api/export.go
  kernel/api/router.go
  kernel/model/export.go
Labels: Development

#8846 When maxListCount limit is not reached, the wrong pop-up box prompts a maxListCount error
  kernel/model/file.go
Labels: Bug
