Repository siyuan-note/siyuan, pull requests merged in 2023-04, with the labels that each got.

#7891 AI translation adds support for `Traditional Chinese`
  app/appearance/langs/en_US.json
  app/appearance/langs/es_ES.json
  app/appearance/langs/fr_FR.json
  app/appearance/langs/zh_CHT.json
  app/appearance/langs/zh_CN.json
  app/src/ai/actions.ts
Labels: Enhancement

#7918 Fix API endpoint URL in fetchPost calls `getBlockInfo`
  app/src/block/Panel.ts
  app/src/window/openNewWindow.ts
Labels: Bug

#7994 Provide useful information for contributors
  scripts/parse-changelog.py
  scripts/win-build.bat
Labels: Development

#7997 Improve automatically remove blank lines in HTML blocks
  app/src/protyle/toolbar/index.ts
Labels: Enhancement

#8002 Fix a fatal error in GitHub Action that casued by electron-builder
  app/package.json
Labels: Development

#8008 Improve automatically add `div` tag in HTML blocks
  app/src/protyle/toolbar/index.ts
Labels: Enhancement

#8012 PWA support (desktop & mobile)
  app/src/assets/template/desktop/index.tpl
  app/src/assets/template/mobile/index.tpl
  app/src/block/popover.ts
  app/src/boot/onGetConfig.ts
  app/src/constants.ts
  app/src/dialog/processSystem.ts
  app/src/index.ts
  app/src/layout/util.ts
  app/src/mobile/index.ts
  app/src/util/functions.ts
  app/src/util/serviceWorker.ts
  app/src/window/onWindowsMsg.ts
  app/stage/auth.html
  app/stage/manifest.webmanifest
  app/stage/service-worker.js
  kernel/model/session.go
  kernel/server/serve.go
Labels: Enhancement

#8001 Import Petal module
  app/package.json
  app/pnpm-lock.yaml
  app/src/index.ts
Labels: Development

#8110 Improve PDF export paging strategy
  app/src/assets/scss/export.scss
Labels: Enhancement
