Repository siyuan-note/siyuan, pull requests merged in 2023-11, with the labels that each got.

#9602 Docker containers run in the background
  README.md
  README_zh_CN.md
Labels: Document

#9280 Improve adaptive width for `Attributes View`
  app/src/assets/scss/business/_av.scss
  app/src/assets/scss/business/_custom.scss
  app/src/assets/scss/component/_tooltips.scss
  app/src/plugin/loader.ts
  app/src/plugin/require.ts
  app/src/protyle/gutter/index.ts
  app/src/protyle/render/av/action.ts
  app/src/protyle/render/av/render.ts
  app/src/protyle/render/av/row.ts
  app/src/protyle/scroll/event.ts
  app/src/protyle/util/resize.ts
  app/src/protyle/wysiwyg/index.ts
  app/src/protyle/wysiwyg/keydown.ts
Labels: Development

#9621 Show card NextDue to the flashcard management UI
  app/appearance/langs/en_US.json
  app/appearance/langs/es_ES.json
  app/appearance/langs/fr_FR.json
  app/appearance/langs/zh_CHT.json
  app/appearance/langs/zh_CN.json
  app/src/card/viewCards.ts
  app/src/types/index.d.ts
  kernel/model/block.go
  kernel/model/flashcard.go
Labels: Enhancement

#9634 Improve localhost address validation
  kernel/model/session.go
  kernel/util/net.go
Labels: Enhancement

#9673 Sort by Due asc on the flashcard management UI
  kernel/model/flashcard.go
Labels: Enhancement

#9679 Docker compose example
  README.md
Labels: Document

#9702 Improve kernel API authentication
  app/src/protyle/util/compatibility.ts
  kernel/api/network.go
  kernel/api/router.go
  kernel/model/session.go
  kernel/util/net.go
Labels: Development

#9722 Add file access control for some kernel APIs
  API.md
  API_zh_CN.md
  kernel/api/archive.go
  kernel/api/file.go
  kernel/util/path.go
Labels: Development

#9729 run js enhance
  app/src/protyle/render/blockRender.ts
Labels: Development
