Repository siyuan-note/siyuan, pull requests merged in 2024-01, with the labels that each got.

#10198 Simplify retry mechanism to get system version
  app/electron/main.js
Labels: Refactor

#10221 Set the maximum message size of WebSocket broadcast to 128 MiB
  kernel/api/broadcast.go
Labels: Development

#10227 Remove invalid requests during boot
  app/electron/boot.html
Labels: Bug
