Repository siyuan-note/siyuan, pull requests merged in 2024-05, with the labels that each got.

#11212 Internationalization supports Japanese
  app/appearance/langs/ja_JP.json
Labels: Enhancement

#11299 Improve user guide
  app/guide/20211226090932-5lcq56f/assets/image-20220119231126-qt2ooye.png
  app/guide/20211226090932-5lcq56f/assets/image-20220803164828-wrh3h5w.png
Labels: Document

#11309 aur auto release
  .github/workflows/auto_aur_release_stable.yml
Labels: Development

#11322 Improve Japanese translation and theme font rendering
  app/appearance/langs/ja_JP.json
  app/appearance/themes/daylight/theme.css
  app/appearance/themes/midnight/theme.css
Labels: Enhancement

#11435 Improve user guide shortcuts chapter
  app/guide/20210808180117-6v0mkxr/20200923234011-ieuun1p/20210808180303-xaduj2o/20200924100950-9op5xi1.sy
  app/guide/20210808180117-czj9bvb/20200812220555-lj3enxa/20210808180321-hbvl5c2/20200813004551-gm0pbn1.sy
  app/guide/20211226090932-5lcq56f/20211226115423-d5z1joq/20211226121203-rjjngpz/20211226122549-jktxego.sy
Labels: Document

#11586 The request of PWA files without `Authentication` Header
  app/src/assets/template/desktop/index.tpl
  app/src/assets/template/mobile/index.tpl
  app/src/util/serviceWorker.ts
Labels: Enhancement
