Repository siyuan-note/siyuan, pull requests merged in 2024-04, with the labels that each got.

#10886 对调数据库中的 More 和 Add 按钮
  app/src/protyle/render/av/render.ts
Labels: Enhancement

#10939 Improve user guide entry
  app/appearance/langs/en_US.json
  app/appearance/langs/es_ES.json
  app/appearance/langs/fr_FR.json
  app/appearance/langs/zh_CHT.json
  app/appearance/langs/zh_CN.json
  app/src/constants.ts
  app/src/layout/status.ts
  app/src/layout/tabUtil.ts
  app/src/menus/workspace.ts
  app/src/mobile/menu/index.ts
  app/src/mobile/util/setEmpty.ts
Labels: Enhancement

#11049 Improve user guide formatting elements and shortcuts chapter
  app/guide/20210808180117-6v0mkxr/20200923234011-ieuun1p/20210808180303-h361q1i/20200924093441-ft2rhps.sy
  app/guide/20210808180117-6v0mkxr/20200923234011-ieuun1p/20210808180303-xaduj2o/20200924100950-9op5xi1.sy
  app/guide/20210808180117-czj9bvb/20200812220555-lj3enxa/20210808180320-abz7w6k/20200825162036-4dx365o.sy
  app/guide/20210808180117-czj9bvb/20200812220555-lj3enxa/20210808180321-hbvl5c2/20200813004551-gm0pbn1.sy
  app/guide/20211226090932-5lcq56f/20211226115423-d5z1joq/20211226120854-dr1jfx2/20211226121319-emrk2yy.sy
  app/guide/20211226090932-5lcq56f/20211226115423-d5z1joq/20211226121203-rjjngpz/20211226122549-jktxego.sy
Labels: Document

#11154 Fix the index task of the embedded block
  kernel/model/index.go
Labels: Bug

#11163 Bazaar count error
  app/src/config/bazaar.ts
Labels: Bug
