Repository siyuan-note/siyuan, pull requests merged in 2024-10, with the labels that each got.

#12663 Improve user guide ignore search chapter
  app/guide/20210808180117-6v0mkxr/20200923234011-ieuun1p/20210808180303-l3qg72k/20240119211017-1vbbt95.sy
  app/guide/20210808180117-6v0mkxr/20200923234011-ieuun1p/20210808180303-l3qg72k/20240119212048-0huuevw.sy
  app/guide/20210808180117-czj9bvb/20200812220555-lj3enxa/20210808180320-gyngv2x/20240119205452-o8xp4ve.sy
  app/guide/20210808180117-czj9bvb/20200812220555-lj3enxa/20210808180320-gyngv2x/20240119205543-hknwwrl.sy
  app/guide/20211226090932-5lcq56f/20211226115423-d5z1joq/20211226120933-vnjgwwh/20240119210914-a2tm8c4.sy
  app/guide/20211226090932-5lcq56f/20211226115423-d5z1joq/20211226120933-vnjgwwh/20240119212000-qkldbjm.sy
  app/guide/20211226090932-5lcq56f/20211226115423-d5z1joq/20211226121203-rjjngpz/20240208171522-y7dxcno.sy
  app/guide/20240530133126-axarxgx/20240530101000-4qitucx/20240530101000-a91lmk2/20240530101000-h0cp5vx.sy
  app/guide/20240530133126-axarxgx/20240530101000-4qitucx/20240530101000-a91lmk2/20240530101000-mrlr6e9.sy
Labels: Document

#12683 Internationalization translations into Hebrew, German, Polish and Russian
  app/appearance/langs/de_DE.json
  app/appearance/langs/he_IL.json
  app/appearance/langs/pl_PL.json
  app/appearance/langs/ru_RU.json
  app/electron/init.html
  app/src/constants.ts
  app/src/types/config.d.ts
  kernel/util/working.go
Labels: Enhancement

#12723 Add a kernel API `/api/block/getDocsInfo`
  kernel/api/block.go
  kernel/api/router.go
  kernel/filesys/tree.go
  kernel/model/blockinfo.go
Labels: Development

#12648 Add `data-id` attribute to the button of workspace menu #12518
  app/src/menus/workspace.ts
Labels: Development

#12701 Improve title menu separator
  app/src/protyle/header/openTitleMenu.ts
Labels: Enhancement

#12739 Improve Russian translation
  app/appearance/langs/ru_RU.json
Labels: Enhancement

#12737 Improve user guide daily notes chapter https://ld246.com/article/1728386759300
  app/guide/20210808180117-6v0mkxr/20200923234011-ieuun1p/20210808180303-xaduj2o/20201204184532-3qm9l8n.sy
  app/guide/20210808180117-6v0mkxr/20200923234011-ieuun1p/20210808180303-xaduj2o/20210110181011-fbhoesf.sy
  app/guide/20210808180117-czj9bvb/20200812220555-lj3enxa/20210808180321-hbvl5c2/20201204181006-7bkppue.sy
  app/guide/20210808180117-czj9bvb/20200812220555-lj3enxa/20210808180321-hbvl5c2/20210110175347-2xrwoiq.sy
  app/guide/20211226090932-5lcq56f/20211226115423-d5z1joq/20211226121203-rjjngpz/20211226123004-dplpw0o.sy
  app/guide/20211226090932-5lcq56f/20211226115423-d5z1joq/20211226121203-rjjngpz/20211226123154-fd5e001.sy
  app/guide/20240530133126-axarxgx/20240530101000-4qitucx/20240530101000-g3ugxml/20240530101000-scr2p21.sy
Labels: Document

#12763 Improve text fix #12351
  app/appearance/langs/de_DE.json
  app/appearance/langs/en_US.json
  app/appearance/langs/es_ES.json
  app/appearance/langs/fr_FR.json
  app/appearance/langs/he_IL.json
  app/appearance/langs/it_IT.json
  app/appearance/langs/ja_JP.json
  app/appearance/langs/pl_PL.json
  app/appearance/langs/ru_RU.json
  app/appearance/langs/zh_CHT.json
  app/appearance/langs/zh_CN.json
Labels: Enhancement

#12850 AUR: remove script that should not be added
  .github/workflows/auto_aur_release_stable.yml
Labels: Enhancement

#12939 Add internal kernel API `/api/icon/getDynamicIcon`
  kernel/api/icon.go
  kernel/api/router.go
Labels: Development
