Repository siyuan-note/siyuan, pull requests merged in 2025-04, with the labels that each got.

#14508 📝修改用户指南快捷键文档中的可能错误
  app/guide/20210808180117-6v0mkxr/20200923234011-ieuun1p/20210808180303-xaduj2o/20200924100950-9op5xi1.sy
  app/guide/20210808180117-czj9bvb/20200812220555-lj3enxa/20210808180321-hbvl5c2/20200813004551-gm0pbn1.sy
  app/guide/20211226090932-5lcq56f/20211226115423-d5z1joq/20211226121203-rjjngpz/20211226122549-jktxego.sy
  app/guide/20240530133126-axarxgx/20240530101000-4qitucx/20240530101000-g3ugxml/20240530101000-xsbxokr.sy
Labels: Document

#14566 Virtual reference cannot jump on mobile
  app/src/protyle/wysiwyg/index.ts
Labels: Bug

#14608 Improve the title of document tree settings on mobile
  app/src/mobile/settings/fileTree.ts
Labels: Enhancement
